### ISSUE TITLE
Generated files should under a directory

### ISSUE THREAD

**Issue by tjyang** [openx/brine#33]
Currently, Generated files are stored in same level as brinefile.
Shouldn't  this  be changed to inside a directory ?
Ex. like rabbitmq elenect example, generated files should be under rabbitmq dir.

**Comment by druonysus** [comment]
Think of it like git, or vagrant, or make... lots of tools work on files in the same directory. I could see where that could be a setting in the `.brinerc` file or `.brine/config`and/or a cli option.
